### ISSUE TITLE
Posture check doesn't work

### ISSUE THREAD

**Issue by jsparber** [MascioSpam/Posture#1]
When I start the posture check it does nothing. My phone is a Galaxy Nexsus with CM12.1 (unofficial). My logcat outputs this 3 lines multiple times:

```
E/BufferQueueProducer(  130): [Sprite] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
E/Surface (  428): dequeueBuffer failed (Function not implemented)
E/Sprites (  428): Error -38 locking sprite surface before drawing.
```

**Comment by jsparber** [comment]
On a Samsung Galaxy s2 plus it does nothing no log or anything.

**Comment by MascioSpam** [comment]
yup :) 
yesterday i forgot to push the last commit and the function wasn't implemented
